variable "ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "vpc_security_group_ids" {}
variable "key_name" {}
variable "iam_instance_profile" {}
variable "volume_size" {}
variable "volume_type" {}
variable "iops" {}
variable "throughput" {}
variable "delete_on_termination" {}
variable "root_block_device_tags_Name" {}
variable "tags_Env" {}
variable "tags_Name" {}